### ISSUE TITLE
Dead link in [README.md]

### ISSUE THREAD

**Issue by eksperimental** [EtiennePerot/parcimonie.sh#14]
https://code.openhub.net/file?fid=BbMaEKchr9cDAOVs8ozX5mJ40g8&cid=RfbvTf3fwdw&s=&browser=Default&fp=405976&mpundefined&projSelected=true?fid=BbMaEKchr9cDAOVs8ozX5mJ40g8&cid=RfbvTf3fwdw&s=&browser=Default&fp=405976&mpundefined&projSelected=true

**Comment by EtiennePerot** [comment]
Fixed in d7d83f0da29d5880da6e8f060fa5e52738e8ae17.
