### ISSUE TITLE
missing license header

### ISSUE THREAD

**Issue by morxa** [EtiennePerot/parcimonie.sh#16]
The Readme states that parcimonie.sh is licensed under WTFPL, but the script does not have any license header.

Could you add the [WTFPL license text](http://www.wtfpl.net/about/) to `parcimonie.sh`?

This was found while reviewing parcimonie.sh for inclusion in Fedora, for details see [this Fedora review request](https://bugzilla.redhat.com/show_bug.cgi?id=1242086).

**Comment by morxa** [comment]
See also [WTFPL FAQ](http://www.wtfpl.net/faq/) for the license header.

**Comment by morxa** [comment]
Any updates on this? I understand this is really a minor issue, but currently that's the only thing blocking parcimonie.sh from being included in Fedora.

Thanks!

**Comment by EtiennePerot** [comment]
Right, sorry, didn't realize it was a blocker.

**Comment by morxa** [comment]
Thanks for fixing this! I'll let you know when parcimonie.sh hits the repositories.
