### ISSUE TITLE
$targetRefreshTime implies the computer is up 24/7

### ISSUE THREAD

**Issue by x4121** [EtiennePerot/parcimonie.sh#20]
The specified $targetRefreshRate only works out if the computer is never turned of. Especially on laptops this is not really feasible. Even worse, with a low number of keys the maximum possible time for any refresh to occur might be higher then the uptime (24h with 14 keys).
Putting the sleep after the refresh would at least ensure one refresh per restart.

**Comment by EtiennePerot** [comment]
Putting the sleep after the refresh would make it possible to correlate key refreshes with specific time patterns (i.e. you turn on your computer at ~regular times over the week → you refresh keys at those same regular intervals), so it would lose some privacy.

I think the best way for this to work is to add a variable like `computerAvailableFraction` that takes a value from 0 (never on) to 1 (always on), and scale the delay by that amount.

**Comment by x4121** [comment]
Well, that makes sense. Didn't thought about that.
I just felt that this might not be obvious for everyone from reading the documentation.

**Comment by EtiennePerot** [comment]
Fixed in 2ce44f45af2f48565aa42155b0bb96f07d373cbc.
