### ISSUE TITLE
Does not torify key fetches with GnuPG 2.1+

### ISSUE THREAD

**Issue by intrigeri** [EtiennePerot/parcimonie.sh#25]
Recent modern GnuPG delegates to dirmngr all keyserver operations. Torifying `gpg` has no effect on how dirmngr reaches keyservers at all. I realize this is being discussed on #15, but if I'm guessing right, this problem entirely prevents parcimonie.sh (sic) from doing its job as designed on recent distros, so it doesn't seem good enough to me to not have this documented anywhere else than on a ticket titled "IPC syntax error with gnupg 2.1.4".

I suggest requesting a CVE for this problem, and documenting this in `README.md` so that new potential users are aware of this limitation.

**Comment by EtiennePerot** [comment]
As per mentioned on that bug, when `dirmngr` is spawned by a torified `gpg`, `dirmngr` inherits the torifiedness, which does make it use Tor for it and subsequent requests, hence the lower severity. You are correct that it does not have the one-unique-circuit-per-refresh property when that happens, though. I will document this on `README.md`.

**Comment by EtiennePerot** [comment]
Done in 0bd6ef34f108ed90c62da7517513f3f00c012595.

**Comment by intrigeri** [comment]
> As per mentioned on that bug, when `dirmngr` is spawned by a torified `gpg`, `dirmngr` inherits the torifiedness,

Cool, thanks for clarifying! I'll check how parcimonie.sh ensures that it uses a newly spawned dirmngr, instead of a pre-existing one. Looks like I may have something to learn in this area :)

**Comment by EtiennePerot** [comment]
It doesn't currently ensure that it's using a new `dirmngr`. This does mean bypassing Tor if the user manually runs `gpg --recv-keys` prior to `parcimonie.sh` doing its first key refresh, which I also documented on commit 0bd6ef34f108ed90c62da7517513f3f00c012595.

I have a proposed solution for ensuring that it uses a new guaranteed-to-be-torified one at https://github.com/EtiennePerot/parcimonie.sh/issues/15#issuecomment-266246661 but I haven't implemented it yet.
