### ISSUE TITLE
PGP key expired

### ISSUE THREAD

**Issue by icetan** [EtiennePerot/parcimonie.sh#30]
Hi,

when I try to install on Arch using `makepkg`, it fails the signature check using `git log`.

It looks like your PGP key expired 2019-01-13. If you still own this key could you update the expiration date and re-publish?

**Comment by genodeftest** [comment]
It looks like this issue has been resolved on the git master branch a few days ago. Would you mind to recheck?

**Comment by icetan** [comment]
Looks like `makepkg` finishes now, cheers!
